plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.5'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'gdg'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	//uuid
	implementation 'co.nlighten:short-uuid:0.1.1'

	//valid
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	//jwt
	implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
	implementation 'jakarta.xml.bind:jakarta.xml.bind-api:4.0.0'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'

	// JSON
	implementation 'com.google.code.gson:gson:2.10.1'
	implementation 'net.minidev:json-smart:2.5.0'

	//jpa
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	runtimeOnly 'com.mysql:mysql-connector-j'

	//security
	implementation 'org.springframework.boot:spring-boot-starter-security'

	//lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	//boot
	implementation 'org.springframework.boot:spring-boot-starter-web'

	//test
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testImplementation'org.springframework.boot:spring-boot-testcontainers'
	testImplementation("org.testcontainers:junit-jupiter")
	testImplementation("org.testcontainers:mysql")

	//firebase
	implementation 'com.google.firebase:firebase-admin:9.2.0'

	//sms
	implementation 'net.nurigo:javaSDK:2.2'
	implementation "org.springframework.boot:spring-boot-starter-data-redis"

	//s3
	implementation 'software.amazon.awssdk:s3:2.20.45'
	implementation 'software.amazon.awssdk:apache-client:2.20.45'
}

tasks.named('test') {
	useJUnitPlatform()
}

jar {
	enabled = false
}

bootJar {
	archiveFileName = 'gdg-0.0.1-SNAPSHOT.jar'
}
